apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argoapps
spec:
  project: default
  source:
    repoURL: https://github.com/pribnoda/argocd.git
    targetRevision: HEAD
    path: ../apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argoapps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true